/*
** EPITECH PROJECT, 2021
** R-type
** File description:
** R-type
*/

#ifndef _SDK_STRUCTURES_KEYBOARD_HPP_
#define _SDK_STRUCTURES_KEYBOARD_HPP_

#include <SFML/Window/Keyboard.hpp>

namespace keyboard {
    enum KeyStatus {
        PRESSED,
        RELEASED
    };

    constexpr auto NB_KEYS = 68;
    enum Key : unsigned {
        LeftClick = 1,
        RightClick,
        A,
        B,
        C,
        D,
        E,
        F,
        G,
        H,
        I,
        J,
        K,
        L,
        M,
        N,
        O,
        P,
        Q,
        R,
        S,
        T,
        U,
        V,
        W,
        X,
        Y,
        Z,
        Num0,
        Num1,
        Num2,
        Num3,
        Num4,
        Num5,
        Num6,
        Num7,
        Num8,
        Num9,
        Escape,
        LControl,
        LShift,
        LAlt,
        RControl,
        RShift,
        RAlt,
        Tab,
        Space,
        Enter,
        BackSpace,
        Left,
        Right,
        Up,
        Down,
        F1,
        F2,
        F3,
        F4,
        F5,
        F6,
        F7,
        F8,
        F9,
        F10,
        F11,
        F12,
        F13,
        F14,
        F15
    };

    constexpr std::array<std::pair<Key, sf::Keyboard::Key>, NB_KEYS> relation_sfml = {{
        {Key::A, sf::Keyboard::Key::A},
        {Key::B, sf::Keyboard::Key::B},
        {Key::C, sf::Keyboard::Key::C},
        {Key::D, sf::Keyboard::Key::D},
        {Key::E, sf::Keyboard::Key::E},
        {Key::F, sf::Keyboard::Key::F},
        {Key::G, sf::Keyboard::Key::G},
        {Key::H, sf::Keyboard::Key::H},
        {Key::I, sf::Keyboard::Key::I},
        {Key::J, sf::Keyboard::Key::J},
        {Key::K, sf::Keyboard::Key::K},
        {Key::L, sf::Keyboard::Key::L},
        {Key::M, sf::Keyboard::Key::M},
        {Key::N, sf::Keyboard::Key::N},
        {Key::O, sf::Keyboard::Key::O},
        {Key::P, sf::Keyboard::Key::P},
        {Key::Q, sf::Keyboard::Key::Q},
        {Key::R, sf::Keyboard::Key::R},
        {Key::S, sf::Keyboard::Key::S},
        {Key::T, sf::Keyboard::Key::T},
        {Key::U, sf::Keyboard::Key::U},
        {Key::V, sf::Keyboard::Key::V},
        {Key::W, sf::Keyboard::Key::W},
        {Key::X, sf::Keyboard::Key::X},
        {Key::Y, sf::Keyboard::Key::Y},
        {Key::Z, sf::Keyboard::Key::Z},
        {Key::Num0, sf::Keyboard::Key::Num0},
        {Key::Num1, sf::Keyboard::Key::Num1},
        {Key::Num2, sf::Keyboard::Key::Num2},
        {Key::Num3, sf::Keyboard::Key::Num3},
        {Key::Num4, sf::Keyboard::Key::Num4},
        {Key::Num5, sf::Keyboard::Key::Num5},
        {Key::Num6, sf::Keyboard::Key::Num6},
        {Key::Num7, sf::Keyboard::Key::Num7},
        {Key::Num8, sf::Keyboard::Key::Num8},
        {Key::Num9, sf::Keyboard::Key::Num9},
        {Key::Escape, sf::Keyboard::Key::Escape},
        {Key::LControl, sf::Keyboard::Key::LControl},
        {Key::LShift, sf::Keyboard::Key::LShift},
        {Key::LAlt, sf::Keyboard::Key::LAlt},
        {Key::RControl, sf::Keyboard::Key::RControl},
        {Key::RShift, sf::Keyboard::Key::RShift},
        {Key::RAlt, sf::Keyboard::Key::RAlt},
        {Key::Tab, sf::Keyboard::Key::Tab},
        {Key::Space, sf::Keyboard::Key::Space},
        {Key::Enter, sf::Keyboard::Key::Enter},
        {Key::BackSpace, sf::Keyboard::Key::BackSpace},
        {Key::Left, sf::Keyboard::Key::Left},
        {Key::Right, sf::Keyboard::Key::Right},
        {Key::Up, sf::Keyboard::Key::Up},
        {Key::Down, sf::Keyboard::Key::Down},
        {Key::F1, sf::Keyboard::Key::F1},
        {Key::F2, sf::Keyboard::Key::F2},
        {Key::F3, sf::Keyboard::Key::F3},
        {Key::F4, sf::Keyboard::Key::F4},
        {Key::F5, sf::Keyboard::Key::F5},
        {Key::F6, sf::Keyboard::Key::F6},
        {Key::F7, sf::Keyboard::Key::F7},
        {Key::F8, sf::Keyboard::Key::F8},
        {Key::F9, sf::Keyboard::Key::F9},
        {Key::F10, sf::Keyboard::Key::F10},
        {Key::F11, sf::Keyboard::Key::F11},
        {Key::F12, sf::Keyboard::Key::F12},
        {Key::F13, sf::Keyboard::Key::F13},
        {Key::F14, sf::Keyboard::Key::F14},
        {Key::F15, sf::Keyboard::Key::F15},
    }};
}

#endif