/*
** EPITECH PROJECT, 2021
** R-type
** File description:
** R-type
*/

#ifndef _SDK_STRUCTURES_KEYBOARD_HPP_
#define _SDK_STRUCTURES_KEYBOARD_HPP_

#include <SFML/Window/Keyboard.hpp>

namespace keyboard {
    enum KeyStatus {
        PRESSED,
        RELEASED
    };

    constexpr auto NB_KEYS = 68;
    enum Key : unsigned {
        LeftClick = 0,
        RightClick = 1,
        A = 2,
        B = 3,
        C = 4,
        D = 5,
        E = 6,
        F = 7,
        G = 8,
        H = 9,
        I = 10,
        J = 11,
        K = 12,
        L = 13,
        M = 14,
        N = 15,
        O = 16,
        P = 17,
        Q = 18,
        R = 19,
        S = 20,
        T = 21,
        U = 22,
        V = 23,
        W = 24,
        X = 25,
        Y = 26,
        Z = 27,
        Num0 = 28,
        Num1 = 29,
        Num2 = 30,
        Num3 = 31,
        Num4 = 32,
        Num5 = 33,
        Num6 = 34,
        Num7 = 35,
        Num8 = 36,
        Num9 = 37,
        Escape = 38,
        LControl = 39,
        LShift = 40,
        LAlt = 41,
        RControl = 42,
        RShift = 43,
        RAlt = 44,
        Tab = 45,
        Space = 46,
        Enter = 47,
        BackSpace = 48,
        Left = 49,
        Right = 50,
        Up = 51,
        Down = 52,
        F1 = 53,
        F2 = 54,
        F3 = 55,
        F4 = 56,
        F5 = 57,
        F6 = 58,
        F7 = 59,
        F8 = 60,
        F9 = 61,
        F10 = 62,
        F11 = 63,
        F12 = 64,
        F13 = 65,
        F14 = 66,
        F15 = 67
    };

    constexpr std::array<std::pair<Key, sf::Keyboard::Key>, NB_KEYS> relation_sfml = {{
        {Key::A, sf::Keyboard::Key::A},
        {Key::B, sf::Keyboard::Key::B},
        {Key::C, sf::Keyboard::Key::C},
        {Key::D, sf::Keyboard::Key::D},
        {Key::E, sf::Keyboard::Key::E},
        {Key::F, sf::Keyboard::Key::F},
        {Key::G, sf::Keyboard::Key::G},
        {Key::H, sf::Keyboard::Key::H},
        {Key::I, sf::Keyboard::Key::I},
        {Key::J, sf::Keyboard::Key::J},
        {Key::K, sf::Keyboard::Key::K},
        {Key::L, sf::Keyboard::Key::L},
        {Key::M, sf::Keyboard::Key::M},
        {Key::N, sf::Keyboard::Key::N},
        {Key::O, sf::Keyboard::Key::O},
        {Key::P, sf::Keyboard::Key::P},
        {Key::Q, sf::Keyboard::Key::Q},
        {Key::R, sf::Keyboard::Key::R},
        {Key::S, sf::Keyboard::Key::S},
        {Key::T, sf::Keyboard::Key::T},
        {Key::U, sf::Keyboard::Key::U},
        {Key::V, sf::Keyboard::Key::V},
        {Key::W, sf::Keyboard::Key::W},
        {Key::X, sf::Keyboard::Key::X},
        {Key::Y, sf::Keyboard::Key::Y},
        {Key::Z, sf::Keyboard::Key::Z},
        {Key::Num0, sf::Keyboard::Key::Num0},
        {Key::Num1, sf::Keyboard::Key::Num1},
        {Key::Num2, sf::Keyboard::Key::Num2},
        {Key::Num3, sf::Keyboard::Key::Num3},
        {Key::Num4, sf::Keyboard::Key::Num4},
        {Key::Num5, sf::Keyboard::Key::Num5},
        {Key::Num6, sf::Keyboard::Key::Num6},
        {Key::Num7, sf::Keyboard::Key::Num7},
        {Key::Num8, sf::Keyboard::Key::Num8},
        {Key::Num9, sf::Keyboard::Key::Num9},
        {Key::Escape, sf::Keyboard::Key::Escape},
        {Key::LControl, sf::Keyboard::Key::LControl},
        {Key::LShift, sf::Keyboard::Key::LShift},
        {Key::LAlt, sf::Keyboard::Key::LAlt},
        {Key::RControl, sf::Keyboard::Key::RControl},
        {Key::RShift, sf::Keyboard::Key::RShift},
        {Key::RAlt, sf::Keyboard::Key::RAlt},
        {Key::Tab, sf::Keyboard::Key::Tab},
        {Key::Space, sf::Keyboard::Key::Space},
        {Key::Enter, sf::Keyboard::Key::Enter},
        {Key::BackSpace, sf::Keyboard::Key::BackSpace},
        {Key::Left, sf::Keyboard::Key::Left},
        {Key::Right, sf::Keyboard::Key::Right},
        {Key::Up, sf::Keyboard::Key::Up},
        {Key::Down, sf::Keyboard::Key::Down},
        {Key::F1, sf::Keyboard::Key::F1},
        {Key::F2, sf::Keyboard::Key::F2},
        {Key::F3, sf::Keyboard::Key::F3},
        {Key::F4, sf::Keyboard::Key::F4},
        {Key::F5, sf::Keyboard::Key::F5},
        {Key::F6, sf::Keyboard::Key::F6},
        {Key::F7, sf::Keyboard::Key::F7},
        {Key::F8, sf::Keyboard::Key::F8},
        {Key::F9, sf::Keyboard::Key::F9},
        {Key::F10, sf::Keyboard::Key::F10},
        {Key::F11, sf::Keyboard::Key::F11},
        {Key::F12, sf::Keyboard::Key::F12},
        {Key::F13, sf::Keyboard::Key::F13},
        {Key::F14, sf::Keyboard::Key::F14},
        {Key::F15, sf::Keyboard::Key::F15},
    }};
}

#endif